CHANGELOG.md, build/azure-pipelines.yml
Add empty azure pipelines.
When this merge I will be able to test my code in #2.
=> ci: Empty Azure Pipelines

CHANGELOG.md, build/stage-release-googleplay.yml, src/app/android/app/src/main/AndroidManifest.xml, src/app/android/app/src/profile/AndroidManifest.xml
We were missing the internet permission on debug for some reason the manifest file was not present like it should by default.
We also added the permission on release mode because we were getting an infinite loading on the Dad Jokes.
Also added a possible fix for the release on Google Play.
Based on your changes these …
=> fix: Android Internet

CHANGELOG.md, tools/copyApplicationTemplate.ps1
No longer copy the source control.
=> fix: Copy script source control

.mergify.yml, CHANGELOG.md
=> ci: Fix mergify

.vscode/launch.json, CHANGELOG.md, build/steps-build-android.yml, build/steps-build-ios.yml, build/steps-build-windows.yml, doc/Diagnostics.md, doc/Environment.md, src/app/.env.dev, src/app/.env.prod, src/app/.env.staging, src/app/.gitignore, src/app/lib/access/environment/environment_repository.dart, src/app/lib/business/environment/environment.dart, src/app/lib/business/environment/environment_manager.dart, src/app/lib/main.dart, src/app/lib/presentation/diagnostic/environment_diagnostic_widget.dart, src/app/lib/presentation/diagnostic/environment_picker_widget.dart, src/app/lib/presentation/diagnostic/expanded_diagnostic_page.dart, src/app/pubspec.lock, src/app/pubspec.yaml
I've implemented the environment logic.
=> Implement environments in the template

doc/Environment.md
In my previous PR #12, I made a last-minute change which I forgot to apply the change on the documentation.
=> docs: rectify environment.md with last minute change from #12

.vscode/launch.json, CHANGELOG.md
Start from debug menu should work now.
=> fix: VS Code Config

CHANGELOG.md, doc/Architecture.md, doc/KillSwitch.md, src/app/lib/access/kill_switch/kill_switch_repository.dart, src/app/lib/access/kill_switch/kill_switch_repository_mock.dart, src/app/lib/app_router.dart, src/app/lib/business/kill_switch/kill_switch_service.dart, src/app/lib/main.dart, src/app/lib/presentation/diagnostic/navigation_diagnostic_widget.dart, src/app/lib/presentation/kill_switch/kill_switch_page.dart
=> feat: add kill switch abstraction

CHANGELOG.md, doc/Architecture.md, doc/Diagnostics.md, doc/Logging.md, src/app/lib/access/environment/environment_repository.dart, src/app/lib/access/logger/custom_console_output.dart, src/app/lib/access/logger/custom_file_output.dart, src/app/lib/access/logger/logger_repository.dart, src/app/lib/access/logger/logging_configuration_data.dart, src/app/lib/access/persistence_exception.dart, src/app/lib/app.dart, src/app/lib/app_router.dart, src/app/lib/app_shell.dart, src/app/lib/business/dad_jokes/dad_jokes_service.dart, src/app/lib/business/environment/environment_manager.dart, src/app/lib/business/logger/level_log_filter.dart, src/app/lib/business/logger/logger_manager.dart, src/app/lib/main.dart, src/app/lib/presentation/diagnostic/device_info_widget.dart, src/app/lib/presentation/diagnostic/diagnostic_switch.dart, src/app/lib/presentation/diagnostic/environment_picker_widget.dart, src/app/lib/presentation/diagnostic/expanded_diagnostic_page.dart, src/app/lib/presentation/diagnostic/logger_diagnostic_widget.dart, src/app/lib/presentation/diagnostic/logging_configuration_widget.dart, src/app/lib/shell.dart, src/app/pubspec.lock, src/app/pubspec.yaml, src/app/test/app_test.dart, src/app/test/business/dad_jokes_service_test.dart
I've implemented logging in the template. I've also done some rework related to shell to ensure the diagnostic has access to a navigator so we can display a native prompt. Finally, I've added a button in diagnostics to open app settings (only for windows)
=> Implement loggers in the template + other improvments

CHANGELOG.md, doc/KillSwitch.md, src/app/lib/access/kill_switch/kill_switch_repository.dart, src/app/lib/main.dart
=> feat: added Firebase implementation of kill switch

CHANGELOG.md, doc/Diagnostics.md, doc/Logging.md, src/app/.env.dev, src/app/.env.prod, src/app/.env.staging, src/app/lib/access/diagnostics/diagnostics_repository.dart, src/app/lib/access/logger/alice_output.dart, src/app/lib/app_router.dart, src/app/lib/business/diagnostics/diagnostics_service.dart, src/app/lib/business/logger/logger_manager.dart, src/app/lib/main.dart, src/app/lib/presentation/diagnostic/diagnostic_overlay.dart, src/app/lib/presentation/diagnostic/environment_diagnostic_widget.dart, src/app/lib/presentation/diagnostic/expanded_diagnostic_page.dart, src/app/lib/presentation/diagnostic/logger_diagnostic_widget.dart, src/app/pubspec.lock, src/app/pubspec.yaml
In this PR, I've integrated Alice in the template to track logs while in-app. I've also took the opportunity to fix the dismiss diagnostic overlay behavior so it's not permanent (just like in the unoapplicationtemplate)
=> Integrate Alice + diagnostic overlay fix

.vscode/launch.json, CHANGELOG.md, build/steps-build-tests.yml, doc/Testing.md, src/app/integration_test/dad_jokes_page_test.dart, src/app/integration_test/integration_test.dart, src/app/integration_test/kill_switch_test.dart, src/app/lib/access/kill_switch/kill_switch_repository_mock.dart, src/app/lib/main.dart, src/app/lib/presentation/diagnostic/navigation_diagnostic_widget.dart, src/app/lib/presentation/kill_switch/kill_switch_page.dart
=> feat: added test for killswitch

build/templates/flutter-install.yml, build/variables.yml, src/app/pubspec.lock, src/app/pubspec.yaml, src/cli/CHANGELOG.md, src/cli/pubspec.yaml
Now targets specific Flutter/Dart SDK.
=> ci: Target specific Dart/Flutter SDK

doc/Architecture.md, doc/AzurePipelines.md, doc/DependencyInjection.md, doc/Diagnostics.md, doc/Environment.md, doc/KillSwitch.md, doc/Navigation.md, doc/Testing.md, src/cli/CHANGELOG.md
- Update `Architecture.md` and its diagrams if you made **architecture …
=> docs: cleanup

build/stage-build.yml, src/cli/CHANGELOG.md
Fix CI so we can deploy the CLI on pub dev.
- Update `Architecture.md` and its …
=> fix: CI iOS artifact

build/stage-build.yml, src/cli/.azuredevops/stage-publish-cli.yml, src/cli/.azuredevops/templates/publish-package.yml, src/cli/CHANGELOG.md, src/cli/pubspec.yaml
Fixes package publishing to pub.dev and adds new logic for generating the build number.
- Update `Diagnostics.md` if you made changes to **diagnostic …
=> fix: Fix package publishing in pub.dev

src/cli/.azuredevops/stage-publish-cli.yml, src/cli/.azuredevops/templates/publish-package.yml, src/cli/CHANGELOG.md
Fixes an issue in which authentication with pub.dev failed, causing the package publish step to fail / be skipped
- Update `Diagnostics.md` if you …
=> fix: Fix CI authentication with pub.dev

README.md, build/steps-build-tests.yml, build/templates/validate-commits.yaml, build/variables.yml, src/app/android/app/build.gradle, src/app/android/gradle.properties, src/app/android/gradle/wrapper/gradle-wrapper.properties, src/app/android/settings.gradle, src/app/ios/Podfile.lock, src/app/lib/main.dart, src/app/pubspec.lock, src/app/pubspec.yaml, src/cli/.azuredevops/templates/publish-package.yml, src/cli/CHANGELOG.md
- Update `Architecture.md` and its diagrams if you made **architecture …
=> Update Flutter to 3.27.3

doc/Architecture.md, src/app/analysis_options.yaml, src/app/lib/app.dart, src/app/lib/presentation/dad_jokes/dad_joke_list_item.dart, src/app/lib/presentation/dad_jokes/dad_jokes_page.dart, src/app/lib/presentation/dad_jokes/dad_jokes_page_viewmodel.dart, src/app/lib/presentation/dad_jokes/favorite_dad_jokes.dart, src/app/lib/presentation/dad_jokes/favorite_dad_jokes_viewmodel.dart, src/app/lib/presentation/mvvm/mvvm_widget.dart, src/app/lib/presentation/mvvm/view_model.dart, src/app/pubspec.lock, src/app/pubspec.yaml, src/cli/CHANGELOG.md, src/mvvm_lints/CHANGELOG.md, src/mvvm_lints/README.md, src/mvvm_lints/analysis_options.yaml, src/mvvm_lints/lib/mvvm_lints.dart, src/mvvm_lints/pubspec.yaml
Replace Riverpod in favor of a custom MVVM recipe using ViewModels to better align with Flutter's recommended app architecture: https://docs.flutter.dev/app-architecture
- Update `AzurePipelines.md` and `src/app/README.md` if you made …
=> feat: Replace Riverpod with custom ViewModels.

README.md, src/cli/CHANGELOG.md
Updated documentation on how to debug the CLI.
- Update `Architecture.md` and …
=> docs: Add Debug Doc for CLI

build/templates/validate-commits.yaml, doc/Localization.md, src/cli/CHANGELOG.md
- fix commit validation after a merge
- update doc on localization
- Update …
=> Fix commit validation 

src/app/ios/Podfile.lock, src/app/ios/Runner.xcodeproj/project.pbxproj, src/app/pubspec.lock, src/cli/CHANGELOG.md
chore: update packages
- Update `Architecture.md` and its diagrams if you made …
=> chore: update packages

build/azure-pipelines.yml, build/stage-release-appstore.yml, build/stage-release-firebase-app-distribution.yml, build/stage-security-scan.yml, build/variables.yml, src/app/README.md, src/app/android/app/build.gradle, src/app/ios/Podfile, src/cli/CHANGELOG.md
update min OS version
update CI/CD
template cleanup
- Update `Architecture.md` …
=> chore: update min OS version & refactor CI/CD

CONTRIBUTING.md, build/azure-pipelines.yml, src/cli/.azuredevops/stage-calculate-pubdev-score.yml, src/cli/.azuredevops/templates/calculate-devscore.yml, src/cli/CHANGELOG.md
Adds an additional CI step for creating a local pub.dev score report
- Update …
=> ci: Add pub.dev calculation step
